[package]
name = "gitbutler-branch"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[dependencies]
anyhow.workspace = true
git2.workspace = true
gix = { workspace = true, features = [] }
gitbutler-reference.workspace = true
gitbutler-diff.workspace = true
gitbutler-stack.workspace = true
but-graph.workspace = true
itertools.workspace = true
serde.workspace = true
bstr.workspace = true
lazy_static = "1.4.0"

[[test]]
name = "branch"
path = "tests/mod.rs"
