[package]
name = "gitbutler-sync"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
tracing.workspace = true
itertools.workspace = true
git2.workspace = true
gix.workspace = true
gitbutler-oplog.workspace = true
gitbutler-command-context.workspace = true
gitbutler-project.workspace = true
gitbutler-user.workspace = true
gitbutler-reference.workspace = true
gitbutler-error.workspace = true
gitbutler-id.workspace = true
gitbutler-url.workspace = true
gitbutler-stack.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-repo.workspace = true
gitbutler-commit.workspace = true
rand = "0.9"
