[package]
name = "but-settings"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
serde_json_lenient.workspace = true
gitbutler-fs.workspace = true
notify.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
but-path.workspace = true

[[test]]
name = "settings"
path = "tests/mod.rs"

[dev-dependencies]
