[package]
name = "gitbutler-diff"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"
autotests = false

[lib]
doctest = false

[dependencies]
git2.workspace = true
bstr.workspace = true
md5.workspace = true
anyhow.workspace = true
hex = "0.4.3"
tracing.workspace = true
gitbutler-serde.workspace = true
gitbutler-command-context.workspace = true
gitbutler-cherry-pick.workspace = true
diffy = "0.4.0"
serde.workspace = true

[[test]]
name = "diff"
path = "tests/mod.rs"
