[package]
name = "but-tools"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false
test = false

[dependencies]
async-openai.workspace = true
serde_json.workspace = true
anyhow.workspace = true
schemars.workspace = true
serde.workspace = true
serde-error = "0.1.3"
bstr.workspace = true
gix.workspace = true
but-core.workspace = true
but-workspace.workspace = true
gitbutler-command-context.workspace = true
gitbutler-oplog.workspace = true
but-graph.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-branch.workspace = true
gitbutler-project.workspace = true
gitbutler-stack.workspace = true
gitbutler-serde.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-reference.workspace = true
but-hunk-dependency.workspace = true
but-hunk-assignment.workspace = true