[package]
name = "gitbutler-forge"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
anyhow.workspace = true
gitbutler-fs.workspace = true
but-github.workspace = true
git-url-parse = "0.6.0"
but-forge-storage.workspace = true
