[package]
name = "but-graph"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
description = "Types to represent Git commit graphs as connected segments, and perform various operations on these."
publish = false
rust-version = "1.89"

[lib]
doctest = false
test = true

[dependencies]
but-core.workspace = true

gix = { workspace = true, features = ["revision"] }
bstr.workspace = true
petgraph = { version = "0.8.3", default-features = false, features = ["stable_graph", "std"] }
anyhow.workspace = true
bitflags.workspace = true

# For `VirtualBranchesTomlRefMetadata` and legacy types
tracing.workspace = true
itertools.workspace = true
toml.workspace = true
serde.workspace = true
gitbutler-serde.workspace = true
md5.workspace = true
gitbutler-reference.workspace = true
hex = "0.4.3"

[dev-dependencies]
gix-testtools.workspace = true
insta = "1.43.2"
but-testsupport.workspace = true

