[package]
name = "but-worktrees"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
but-workspace.workspace = true
but-graph.workspace = true
but-status.workspace = true
but-rebase.workspace = true
but-core.workspace = true
gix.workspace = true
gitbutler-command-context.workspace = true
gitbutler-project.workspace = true
gitbutler-stack.workspace = true
gitbutler-oxidize.workspace = true
gitbutler-workspace.workspace = true
gitbutler-branch-actions.workspace = true
serde.workspace = true
uuid.workspace = true
bstr.workspace = true
tracing.workspace = true

[dev-dependencies]
gix-testtools.workspace = true
gitbutler-branch-actions.workspace = true
gitbutler-testsupport.workspace = true
gitbutler-oxidize.workspace = true
insta.workspace = true
but-testsupport.workspace = true
